"""add profile fields to user

Revision ID: e7d4308e5f01
Revises: e9c40a7deaf4
Create Date: 2026-07-20 12:57:47.538892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e7d4308e5f01'
down_revision: Union[str, Sequence[str], None] = 'e9c40a7deaf4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('profile_picture', sa.String(), nullable=True))
    op.add_column(
        "users",
        sa.Column(
            "currency",
            sa.String(length=3),
            server_default=sa.text("'INR'"),
            nullable=False
        )
    )
    op.add_column(
        "users",
        sa.Column(
            "timezone",
            sa.String(length=50),
            server_default=sa.text("'Asia/Kolkata'"),
            nullable=False
        )
    )
    op.add_column('users', sa.Column('monthly_income', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('users', sa.Column('monthly_salary_date', sa.Integer(), nullable=True))
    op.alter_column(
        "users",
        "currency",
        server_default=None
    )

    op.alter_column(
        "users",
        "timezone",
        server_default=None
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'monthly_salary_date')
    op.drop_column('users', 'monthly_income')
    op.drop_column('users', 'timezone')
    op.drop_column('users', 'currency')
    op.drop_column('users', 'profile_picture')
    op.drop_column('users', 'name')
    # ### end Alembic commands ###
