"""add soft delete support

Revision ID: e9c40a7deaf4
Revises: 368893729ff1
Create Date: 2026-06-18 11:21:33.275796

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9c40a7deaf4'
down_revision: Union[str, Sequence[str], None] = '368893729ff1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('expenses', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_deleted')
    op.drop_column('expenses', 'is_deleted')
    op.drop_column('category', 'is_deleted')
    # ### end Alembic commands ###
